# Generated by Django 6.0.1 on 2026-01-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_transaction_id'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to='payments.payment'),
        ),
    ]
