# Generated by Django 4.1.13 on 2026-01-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Seat number', unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance')], default='available', help_text='Current status of the seat', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the seat', null=True, upload_to='seats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Booking start time')),
                ('end_time', models.DateTimeField(help_text='Booking end time')),
                ('plan', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], help_text='Booking plan type', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Booking status', max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Payment screenshot for online payments', null=True, upload_to='payments/')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total booking amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat', models.ForeignKey(help_text='Seat being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='seats.seat')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('seat', 'start_time', 'end_time')},
            },
        ),
    ]
