# Generated by Django 4.1.13 on 2026-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='payment_id',
            field=models.PositiveIntegerField(blank=True, help_text='Reference to the payment record', null=True),
        ),
    ]
