# Generated by Django 4.1.13 on 2026-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seatbooking_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatbooking',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='seat',
            name='photo',
            field=models.URLField(blank=True, help_text='Photo URL of the seat', max_length=500, null=True),
        ),
    ]
