# Generated by Django 4.1.13 on 2026-01-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_remove_seatbooking_payment_id_alter_seat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='payment_id',
            field=models.PositiveIntegerField(blank=True, help_text='Payment ID from payment system', null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the seat', null=True, upload_to='seats/'),
        ),
    ]
