# Generated by Django 4.1.13 on 2026-01-15 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0004_seatbooking_payment_id_alter_seat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
