# Generated by Django 4.1.13 on 2026-01-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0005_alter_seatbooking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=set(),
        ),
    ]
