# Generated by Django 6.0.1 on 2026-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_alter_seatbooking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance')], default='available', help_text='Current status of the seat', max_length=20),
        ),
    ]
