# Generated by Django 6.0.2 on 2026-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scan_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scan_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scanned_qr_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
