# Generated by Django 6.0.1 on 2026-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
