# Generated by Django 6.0.1 on 2026-01-16 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Payment description (e.g., Membership Fee)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Payment method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', help_text='Payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, help_text='Account holder name', max_length=200, null=True)),
                ('date', models.DateField(help_text='Payment date')),
                ('screenshot', models.ImageField(blank=True, help_text='Payment screenshot', null=True, upload_to='payments/')),
                ('membership_plan', models.PositiveIntegerField(blank=True, help_text='Membership plan ID if applicable', null=True)),
                ('plan_name', models.CharField(blank=True, help_text='Plan name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
