# Generated by Django 6.0.2 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_comfortable_chairs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_led_lighting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_personal_charging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_ro_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='includes_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('morning_shift', 'Morning Shift (6 AM - 11 AM)'), ('afternoon_shift', 'Afternoon Shift (11 AM - 4 PM)'), ('evening_shift', 'Evening Shift (4 PM - 9 PM)'), ('full_day', 'Full Day (12 Hours)'), ('night_shift', 'Night Shift (7 PM - 6 AM)'), ('24_7_access', '24/7 Access (Unlimited)'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=20, unique=True),
        ),
    ]
